WIP

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,13 +1,30 @@
 # This workflow will install Python dependencies, run tests and lint with a single version of Python
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Python application
+name: Prog 2 Practice
 
 on:
   push:
     branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+  workflow_dispatch:
+    inputs:
+      tp:
+        type: choice
+        description: 'tp to hand-in. Select all to run all tests'
+        required: true
+        options:
+          - tp-1
+          - tp-2
+          - tp-3
+          - tp-4
+          - tp-5
+          - tp-6
+          - tp-7
+      publish_tps:
+        type: boolean
+        description: 'True if you want to hand-in, False otherwise for running all tests'
+        required: true
+        default: False
 
 permissions:
   contents: read
@@ -37,3 +54,12 @@ jobs:
     - name: Test with pytest
       run: |
         pytest
+    - if: inputs.publish_tps == 'true'
+      name: Publish Artifacts
+      run: |
+        pytest ${{ inputs.tp }} 
+        if [ $? -eq 0 ]; then
+          echo "${{ inputs.tp }} Successfully handed-in!"
+        else
+          echo "Cannot hand-in ${{ inputs.tp }} because it has errors!"
+        fi
